plugins: 
  - "stylelint-order"
extends: 
  - "stylelint-config-standard"
ignoreFiles:
  - "**/*.{js,jsx,ts,tsx}"
rules:
  "order/order":
    - - "custom-properties"
      - "declarations"
      - "rules"
      - "at-rules"
    - unspecified: "bottom"
  "order/properties-order":
    - "display"
    - "flex"
    - "flex-grow"
    - "flex-shrink"
    - "flex-basis"
    - "flex-direction"
    - "order"
    - "flex-order"
    - "flex-wrap"
    - "flex-flow"
    - "justify-content"
    - "align-self"
    - "align-items"
    - "align-content"
    - "flex-pack"
    - "flex-align"
    - "float"
    - "clear"
    - "box-sizing"
    - "box-decoration-break"
    - "box-shadow"
    - "position"
    - "top"
    - "right"
    - "bottom"
    - "left"
    - "z-index"
    - "margin"
    - "margin-top"
    - "margin-right"
    - "margin-bottom"
    - "margin-left"
    - "padding"
    - "padding-top"
    - "padding-right"
    - "padding-bottom"
    - "padding-left"
    - "width"
    - "min-width"
    - "max-width"
    - "height"
    - "min-height"
    - "max-height"
    - "overflow"
    - "overflow-x"
    - "overflow-y"
    - "vertical-align"
    - "list-style"
    - "list-style-position"
    - "list-style-type"
    - "list-style-image"
    - "columns"
    - "column-span"
    - "column-width"
    - "column-fill"
    - "column-gap"
    - "column-rule"
    - "column-rule-width"
    - "column-rule-style"
    - "column-rule-color"
    - "color"
    - "font"
    - "font-family"
    - "font-size"
    - "font-size-adjust"
    - "font-stretch"
    - "font-weight"
    - "font-style"
    - "font-variant"
    - "word-spacing"
    - "word-break"
    - "overflow-wrap"
    - "white-space"
    - "tab-size"
    - "hyphens"
    - "src"
    - "line-height"
    - "letter-spacing"
    - "text-align"
    - "text-align-last"
    - "text-decoration"
    - "text-emphasis"
    - "text-emphasis-position"
    - "text-emphasis-style"
    - "text-emphasis-color"
    - "text-indent"
    - "text-justify"
    - "text-outline"
    - "text-transform"
    - "text-wrap"
    - "text-overflow"
    - "text-overflow-ellipsis"
    - "text-overflow-mode"
    - "text-shadow"
    - "border"
    - "border-spacing"
    - "border-collapse"
    - "border-width"
    - "border-style"
    - "border-color"
    - "border-top"
    - "border-top-width"
    - "border-top-style"
    - "border-top-color"
    - "border-right"
    - "border-right-width"
    - "border-right-style"
    - "border-right-color"
    - "border-bottom"
    - "border-bottom-width"
    - "border-bottom-style"
    - "border-bottom-color"
    - "border-left"
    - "border-left-width"
    - "border-left-style"
    - "border-left-color"
    - "border-radius"
    - "border-top-left-radius"
    - "border-top-right-radius"
    - "border-bottom-right-radius"
    - "border-bottom-left-radius"
    - "border-image"
    - "border-image-source"
    - "border-image-slice"
    - "border-image-width"
    - "border-image-outset"
    - "border-image-repeat"
    - "border-top-image"
    - "border-right-image"
    - "border-bottom-image"
    - "border-left-image"
    - "border-corner-image"
    - "border-top-left-image"
    - "border-top-right-image"
    - "border-bottom-right-image"
    - "border-bottom-left-image"
    - "background"
    - "background-color"
    - "background-image"
    - "background-attachment"
    - "background-position"
    - "background-position-x"
    - "background-position-y"
    - "background-repeat"
    - "background-clip"
    - "background-origin"
    - "background-size"
    - "clip"
    - "filter"
    - "outline"
    - "outline-width"
    - "outline-style"
    - "outline-color"
    - "outline-offset"
    - "table-layout"
    - "caption-side"
    - "empty-cells"
    - "quotes"
    - "content"
    - "counter-increment"
    - "counter-reset"
    - "opacity"
    - "visibility"
    - "filter"
    - "resize"
    - "cursor"
    - "nav-index"
    - "nav-up"
    - "nav-right"
    - "nav-down"
    - "nav-left"
    - "transition"
    - "transition-property"
    - "transition-duration"
    - "transition-delay"
    - "transition-timing-function"
    - "transform"
    - "transform-origin"
    - "animation"
    - "animation-name"
    - "animation-duration"
    - "animation-play-state"
    - "animation-timing-function"
    - "animation-delay"
    - "animation-iteration-count"
    - "animation-direction"
    - "pointer-events"
    - "unicode-bidi"
    - "direction"
    - "break-before"
    - "break-inside"
    - "break-after"
    - "page-break-before"
    - "page-break-inside"
    - "page-break-after"
    - "orphans"
    - "widows"
    - "zoom"
    - "max-zoom"
    - "min-zoom"
    - "user-zoom"
    - "orientation"
